import { View, Text, StyleSheet, Pressable } from 'react-native';
import { Link, type Href } from 'expo-router';
import { useTranslation } from 'react-i18next';
import type { ExpensePublic } from '../api/hooks/useExpenses';
import { formatMoney } from '../util/format';
import { formatDateAU } from '../util/dates';
import { StatusBadge } from '../ui/kit';
import { tokens } from '../ui/tokens';
import { useScaledStyles } from '../ui/type';

/**
 * Shared expense row visual.
 *
 * M2-B: extracted verbatim from `RecentCapturesList` so the Last-5
 * list, the per-job expense list, and the new full expenses list all
 * render the identical row (amount + status pill, date · job,
 * preview line, duplicate / receipt-later flags). One implementation,
 * one place to change.
 *
 * Each row is a tappable Link to the detail screen at
 * `/expenses/{expense_id}`. The `as Href` cast bridges expo-router's
 * typed-routes manifest (regenerated by Metro on file changes);
 * runtime behaviour is unchanged.
 *
 * B4-1: the old from=job return-path params are retired — the detail
 * screen's back() naturally returns to whatever pushed it (job page,
 * list, Home) under the root Stack.
 */

// UI-kit v2: status colours live in src/ui/kit.tsx (StatusBadge),
// which keeps the C-04 unknown-enum grey fallback.

const PREVIEW_MAX = 60;

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max).trimEnd() + '…';
}

export function ExpenseRow({
  expense,
  jobName,
}: {
  expense: ExpensePublic;
  jobName: string | undefined;
}) {
  const { t } = useTranslation();
  // B3: two-line font-scale adoption — fixes the mixed-scaling nit
  // (embedded StatusBadge scaled while the row text did not).
  const s = useScaledStyles(base);
  const statusKey = `expense.status_${expense.review_status}`;
  const previewSource = expense.raw_input_text || expense.description || '';
  const preview = truncate(previewSource, PREVIEW_MAX);

  const detailHref =
    `/expenses/${expense.expense_id}` as unknown as Href;
  return (
    <Link href={detailHref} asChild>
      <Pressable
        testID={`recent-row-${expense.expense_id}`}
        accessibilityRole="button"
        accessibilityLabel={`${expense.expense_date} ${expense.amount_inc_gst}`}
        hitSlop={4}
        style={({ pressed }) => [s.row, pressed && s.rowPressed]}
      >
        <View style={s.rowTop}>
          <Text style={s.amount}>{formatMoney(expense.amount_inc_gst)}</Text>
          <StatusBadge
            status={expense.review_status}
            label={t(statusKey, { defaultValue: expense.review_status })}
          />
        </View>

        <View style={s.rowMid}>
          <Text style={s.date}>{formatDateAU(expense.expense_date)}</Text>
          {jobName ? <Text style={s.dot}> · </Text> : null}
          {jobName ? (
            <Text style={s.job} numberOfLines={1}>
              {jobName}
            </Text>
          ) : null}
        </View>

        <Text
          style={preview ? s.preview : s.previewMuted}
          numberOfLines={1}
          testID={`recent-row-${expense.expense_id}-preview`}
        >
          {preview || '—'}
        </Text>

        {(expense.duplicate_flag || expense.receipt_status === 'expected_later') && (
          <View style={s.rowFlags}>
            {expense.duplicate_flag ? (
              <View
                style={[s.flagPill, s.flagDuplicate]}
                testID={`recent-row-${expense.expense_id}-duplicate`}
              >
                <Text style={s.flagText}>{t('capture.recent.duplicate_flag')}</Text>
              </View>
            ) : null}
            {expense.receipt_status === 'expected_later' ? (
              <View
                style={[s.flagPill, s.flagReceipt]}
                testID={`recent-row-${expense.expense_id}-receipt`}
              >
                <Text style={s.flagText}>{t('capture.recent.receipt_later_flag')}</Text>
              </View>
            ) : null}
          </View>
        )}
      </Pressable>
    </Link>
  );
}

const base = StyleSheet.create({
  row: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: tokens.surface,
  },
  rowPressed: {
    backgroundColor: '#f1f5f9',
  },
  rowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  amount: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    fontVariant: ['tabular-nums'],
  },
  rowMid: { flexDirection: 'row', marginTop: 4, alignItems: 'center' },
  date: { color: '#64748b', fontSize: 13 },
  dot: { color: '#94a3b8', fontSize: 13 },
  job: { color: '#64748b', fontSize: 13, flexShrink: 1 },
  preview: { color: '#334155', fontSize: 13, marginTop: 4 },
  previewMuted: { color: '#94a3b8', fontSize: 13, marginTop: 4 },
  rowFlags: { flexDirection: 'row', marginTop: 6 },
  flagPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 6,
  },
  flagDuplicate: { backgroundColor: '#fef3c7' },
  flagReceipt: { backgroundColor: '#e0e7ff' },
  flagText: { fontSize: 10, fontWeight: '600', color: '#1e293b' },
});
