import { View, Text, StyleSheet, Pressable } from 'react-native';
import { Link, type Href } from 'expo-router';
import { useTranslation } from 'react-i18next';
import type { ExpensePublic } from '../api/hooks/useExpenses';
import { formatMoney } from '../util/format';
import { formatDateAU } from '../util/dates';
import { StatusBadge } from '../ui/kit';
import { tokens } from '../ui/tokens';
import { useScaledStyles } from '../ui/type';

/**
 * Shared expense row visual.
 *
 * M2-B: extracted verbatim from `RecentCapturesList` so the Last-5
 * list, the per-job expense list, and the new full expenses list all
 * render the identical row (amount + status pill, date · job,
 * preview line, duplicate / receipt-later flags). One implementation,
 * one place to change.
 *
 * Each row is a tappable Link to the detail screen at
 * `/expenses/{expense_id}`. The `as Href` cast bridges expo-router's
 * typed-routes manifest (regenerated by Metro on file changes);
 * runtime behaviour is unchanged.
 *
 * B4-1: the old from=job return-path params are retired — the detail
 * screen's back() naturally returns to whatever pushed it (job page,
 * list, Home) under the root Stack.
 */

// UI-kit v2: status colours live in src/ui/kit.tsx (StatusBadge),
// which keeps the C-04 unknown-enum grey fallback.

const PREVIEW_MAX = 60;

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max).trimEnd() + '…';
}

export function ExpenseRow({
  expense,
  jobName,
}: {
  expense: ExpensePublic;
  jobName: string | undefined;
}) {
  const { t } = useTranslation();
  // B3: two-line font-scale adoption — fixes the mixed-scaling nit
  // (embedded StatusBadge scaled while the row text did not).
  const s = useScaledStyles(base);
  const statusKey = `expense.status_${expense.review_status}`;
  const previewSource = expense.raw_input_text || expense.description || '';
  const preview = truncate(previewSource, PREVIEW_MAX);

  const detailHref =
    `/expenses/${expense.expense_id}` as unknown as Href;
  return (
    <Link href={detailHref} asChild>
      <Pressable
        testID={`recent-row-${expense.expense_id}`}
        accessibilityRole="button"
        accessibilityLabel={`${expense.expense_date} ${expense.amount_inc_gst}`}
        hitSlop={4}
        style={({ pressed }) => [s.row, pressed && s.rowPressed]}
      >
        <View style={s.rowTop}>
          <Text style={s.amount}>{formatMoney(expense.amount_inc_gst)}</Text>
          <StatusBadge
            status={expense.review_status}
            label={t(statusKey, { defaultValue: expense.review_status })}
          />
        </View>

        <View style={s.rowMid}>
          <Text style={s.date}>{formatDateAU(expense.expense_date)}</Text>
          {jobName ? <Text style={s.dot}> · </Text> : null}
          {jobName ? (
            <Text style={s.job} numberOfLines={1}>
              {jobName}
            </Text>
          ) : null}
        </View>

        <Text
          style={preview ? s.preview : s.previewMuted}
          numberOfLines={1}
          testID={`recent-row-${expense.expense_id}-preview`}
        >
          {preview || '—'}
        </Text>

        {(expense.duplicate_flag || expense.receipt_status === 'expected_later') && (
          <View style={s.rowFlags}>
            {expense.duplicate_flag ? (
              <View
                style={[s.flagPill, s.flagDuplicate]}
                testID={`recent-row-${expense.expense_id}-duplicate`}
              >
                <Text style={s.flagText}>{t('capture.recent.duplicate_flag')}</Text>
              </View>
            ) : null}
            {expense.receipt_status === 'expected_later' ? (
              <View
                style={[s.flagPill, s.flagReceipt]}
                testID={`recent-row-${expense.expense_id}-receipt`}
              >
                <Text style={s.flagText}>{t('capture.recent.receipt_later_flag')}</Text>
              </View>
            ) : null}
          </View>
        )}
      </Pressable>
    </Link>
  );
}

// forey F3 (handoff §5): each expense is a CARD on the grey ground —
// amount 16.5/800 anchored left, badge right, description, date · job.
// One shared visual: the full list, per-job tab and Last-5 all change
// together. marginBottom carries the card gap in every host (bare
// wrappers and FlatLists alike).
const base = StyleSheet.create({
  row: {
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.line,
    borderRadius: 14,
    paddingHorizontal: 13,
    paddingVertical: 12,
    marginBottom: 10,
  },
  rowPressed: { opacity: 0.85 },
  rowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  amount: {
    flexShrink: 1,
    fontSize: 16.5,
    fontWeight: '800',
    color: tokens.ink,
    fontVariant: ['tabular-nums'],
    letterSpacing: -0.2,
  },
  rowMid: { flexDirection: 'row', marginTop: 5, alignItems: 'center' },
  date: { color: tokens.muted, fontSize: 11.5 },
  dot: { color: tokens.muted, fontSize: 11.5 },
  job: { color: tokens.muted, fontSize: 11.5, flexShrink: 1 },
  preview: { color: tokens.ink2, fontSize: 13, marginTop: 3 },
  previewMuted: { color: tokens.muted, fontSize: 13, marginTop: 3 },
  rowFlags: { flexDirection: 'row', marginTop: 7 },
  flagPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    marginRight: 6,
  },
  flagDuplicate: { backgroundColor: tokens.warnBg, borderColor: tokens.warnBorder },
  flagReceipt: { backgroundColor: tokens.sel, borderColor: tokens.selBorder },
  flagText: { fontSize: 10, fontWeight: '700', color: tokens.ink2 },
});
