import { View, Text, StyleSheet, Pressable } from 'react-native';
import { Link, type Href } from 'expo-router';
import { useTranslation } from 'react-i18next';
import type { ExpensePublic } from '../api/hooks/useExpenses';
import { formatMoney } from '../util/format';
import { formatDateAU } from '../util/dates';

/**
 * Shared expense row visual.
 *
 * M2-B: extracted verbatim from `RecentCapturesList` so the Last-5
 * list, the per-job expense list, and the new full expenses list all
 * render the identical row (amount + status pill, date · job,
 * preview line, duplicate / receipt-later flags). One implementation,
 * one place to change.
 *
 * Each row is a tappable Link to the detail screen at
 * `/expenses/{expense_id}`. The `as Href` cast bridges expo-router's
 * typed-routes manifest (regenerated by Metro on file changes);
 * runtime behaviour is unchanged.
 *
 * When rendered inside a job-context list, `fromJobId` appends
 * `?from=job&jobId=...` so the detail screen returns to the Jobs tab
 * modal rather than the originating screen on back/delete.
 */

const STATUS_COLORS = {
  pending: { bg: '#fef3c7', fg: '#92400e' },
  reviewed: { bg: '#dcfce7', fg: '#15803d' },
  rejected: { bg: '#fee2e2', fg: '#991b1b' },
} as const;

// Audit C-04: neutral fallback for a review_status THIS build doesn't
// know — a newer backend enum must degrade to a grey pill, not crash
// every expense row in the list.
const FALLBACK_COLOR = { bg: '#f1f5f9', fg: '#475569' };

const PREVIEW_MAX = 60;

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max).trimEnd() + '…';
}

export function ExpenseRow({
  expense,
  jobName,
  fromJobId,
}: {
  expense: ExpensePublic;
  jobName: string | undefined;
  fromJobId?: string;
}) {
  const { t } = useTranslation();
  const statusColor = STATUS_COLORS[expense.review_status] ?? FALLBACK_COLOR;
  const statusKey = `expense.status_${expense.review_status}`;
  const previewSource = expense.raw_input_text || expense.description || '';
  const preview = truncate(previewSource, PREVIEW_MAX);

  const detailHref = (
    fromJobId
      ? `/expenses/${expense.expense_id}?from=job&jobId=${fromJobId}`
      : `/expenses/${expense.expense_id}`
  ) as unknown as Href;
  return (
    <Link href={detailHref} asChild>
      <Pressable
        testID={`recent-row-${expense.expense_id}`}
        accessibilityRole="button"
        accessibilityLabel={`${expense.expense_date} ${expense.amount_inc_gst}`}
        hitSlop={4}
        style={({ pressed }) => [s.row, pressed && s.rowPressed]}
      >
        <View style={s.rowTop}>
          <Text style={s.amount}>{formatMoney(expense.amount_inc_gst)}</Text>
          <View style={[s.pill, { backgroundColor: statusColor.bg }]}>
            <Text style={[s.pillText, { color: statusColor.fg }]}>
              {t(statusKey, { defaultValue: expense.review_status })}
            </Text>
          </View>
        </View>

        <View style={s.rowMid}>
          <Text style={s.date}>{formatDateAU(expense.expense_date)}</Text>
          {jobName ? <Text style={s.dot}> · </Text> : null}
          {jobName ? (
            <Text style={s.job} numberOfLines={1}>
              {jobName}
            </Text>
          ) : null}
        </View>

        <Text
          style={preview ? s.preview : s.previewMuted}
          numberOfLines={1}
          testID={`recent-row-${expense.expense_id}-preview`}
        >
          {preview || '—'}
        </Text>

        {(expense.duplicate_flag || expense.receipt_status === 'expected_later') && (
          <View style={s.rowFlags}>
            {expense.duplicate_flag ? (
              <View
                style={[s.flagPill, s.flagDuplicate]}
                testID={`recent-row-${expense.expense_id}-duplicate`}
              >
                <Text style={s.flagText}>{t('capture.recent.duplicate_flag')}</Text>
              </View>
            ) : null}
            {expense.receipt_status === 'expected_later' ? (
              <View
                style={[s.flagPill, s.flagReceipt]}
                testID={`recent-row-${expense.expense_id}-receipt`}
              >
                <Text style={s.flagText}>{t('capture.recent.receipt_later_flag')}</Text>
              </View>
            ) : null}
          </View>
        )}
      </Pressable>
    </Link>
  );
}

const s = StyleSheet.create({
  row: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  rowPressed: {
    backgroundColor: '#f1f5f9',
  },
  rowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  amount: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    fontVariant: ['tabular-nums'],
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    overflow: 'hidden',
  },
  pillText: { fontSize: 11, fontWeight: '600' },
  rowMid: { flexDirection: 'row', marginTop: 4, alignItems: 'center' },
  date: { color: '#64748b', fontSize: 13 },
  dot: { color: '#94a3b8', fontSize: 13 },
  job: { color: '#64748b', fontSize: 13, flexShrink: 1 },
  preview: { color: '#334155', fontSize: 13, marginTop: 4 },
  previewMuted: { color: '#94a3b8', fontSize: 13, marginTop: 4 },
  rowFlags: { flexDirection: 'row', marginTop: 6 },
  flagPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 6,
  },
  flagDuplicate: { backgroundColor: '#fef3c7' },
  flagReceipt: { backgroundColor: '#e0e7ff' },
  flagText: { fontSize: 10, fontWeight: '600', color: '#1e293b' },
});
