/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email + password for an access/refresh token pair.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the user identified by the bearer access token.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Issue a new access token given a valid, unexpired refresh token.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Stateless logout: the server does not (yet) revoke anything.
         *
         *     Phase 6 will add a ``jti`` blacklist check here so tokens issued
         *     before logout stop being accepted for the remainder of their TTL.
         *     Until then, clients simply discard their stored tokens.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List categories ordered by ``display_order``.
         */
        get: operations["list_categories_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description Create a category (admin only).
         */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Category
         * @description Partially update a category (admin only).
         */
        patch: operations["update_category_categories__category_id__patch"];
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs Endpoint
         * @description List all jobs (any authenticated caller).
         */
        get: operations["list_jobs_endpoint_jobs_get"];
        put?: never;
        /**
         * Create Job Endpoint
         * @description Create a job (admin only).
         */
        post: operations["create_job_endpoint_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Endpoint
         * @description Fetch a job with its aliases + category budgets eager-loaded.
         */
        get: operations["get_job_endpoint_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Job Endpoint
         * @description Partially update a job (admin only).
         */
        patch: operations["update_job_endpoint_jobs__job_id__patch"];
        trace?: never;
    };
    "/jobs/{job_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Alias Endpoint
         * @description Attach an alias to a job (admin only).
         *
         *     409 on a duplicate normalised alias (globally unique — see the
         *     ``JobAlias`` model's uniqueness contract).
         */
        post: operations["add_alias_endpoint_jobs__job_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/category-budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Category Budget Endpoint
         * @description Attach a per-category budget row to a job (admin only).
         *
         *     404 if either the job or the category doesn't exist. 409 on a
         *     duplicate ``(job_id, category_id)`` pair.
         */
        post: operations["add_category_budget_endpoint_jobs__job_id__category_budgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users Endpoint
         * @description Return every user. Admin only.
         */
        get: operations["list_users_endpoint_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite User Endpoint
         * @description Create a user from an admin-supplied ``initial_password``.
         *
         *     Phase 1 has no email delivery; the admin is expected to communicate
         *     the password to the invitee out of band. Phase 6 will add a proper
         *     magic-link / reset-password flow.
         *
         *     Returns 201 with the new :class:`UserPublic`. A pre-existing user
         *     with the same email produces a 409.
         */
        post: operations["invite_user_endpoint_users_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Endpoint
         * @description Partially update a user. Admin only.
         *
         *     Any subset of ``full_name``, ``role``, ``is_active``, and
         *     ``language_preference`` may be supplied. Setting ``is_active=False``
         *     forces the target's existing access tokens to 401 on the next auth
         *     check — :func:`app.deps.get_current_user` rejects deactivated users.
         */
        patch: operations["update_user_endpoint_users__user_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessToken
         * @description Single-token response returned by ``POST /auth/refresh``.
         */
        AccessToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * CategoryCreate
         * @description Body of ``POST /categories`` (admin-only).
         */
        CategoryCreate: {
            /** Category Name */
            category_name: string;
            /** Display Order */
            display_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * CategoryPublic
         * @description Serialised view of a :class:`~app.models.category.Category` row.
         */
        CategoryPublic: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Display Order */
            display_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * CategoryUpdate
         * @description Body of ``PATCH /categories/{category_id}`` (admin-only).
         */
        CategoryUpdate: {
            /** Category Name */
            category_name?: string | null;
            /** Display Order */
            display_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobAliasCreate
         * @description Body of ``POST /jobs/{job_id}/aliases`` (admin-only).
         */
        JobAliasCreate: {
            /** Alias Text */
            alias_text: string;
            language_code?: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * JobAliasPublic
         * @description Serialised view of a :class:`~app.models.job.JobAlias`.
         */
        JobAliasPublic: {
            /**
             * Alias Id
             * Format: uuid
             */
            alias_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Alias Text */
            alias_text: string;
            /** Alias Text Normalized */
            alias_text_normalized: string;
            language_code: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * JobCategoryBudgetCreate
         * @description Body of ``POST /jobs/{job_id}/category-budgets`` (admin-only).
         */
        JobCategoryBudgetCreate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Budget Amount Ex Gst */
            budget_amount_ex_gst: number | string;
        };
        /**
         * JobCategoryBudgetPublic
         * @description Serialised view of a :class:`~app.models.job.JobCategoryBudget`.
         *
         *     The nested ``category`` is eager-loaded via the ``lazy="joined"``
         *     relationship on the model, so the HTTP response always carries the
         *     category's public shape inline — no extra round trip.
         */
        JobCategoryBudgetPublic: {
            /**
             * Budget Id
             * Format: uuid
             */
            budget_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Budget Amount Ex Gst */
            budget_amount_ex_gst: string;
            category: components["schemas"]["CategoryPublic"];
        };
        /**
         * JobCreate
         * @description Body of ``POST /jobs`` (admin-only).
         */
        JobCreate: {
            /** Job Name */
            job_name: string;
            /** Job Code */
            job_code?: string | null;
            /** Site Address */
            site_address?: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst?: number | string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst?: number | string | null;
            /** @default active */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobPublic
         * @description Compact serialised view of a :class:`~app.models.job.Job`.
         *
         *     Used by ``GET /jobs`` (list) and by non-detail POST/PATCH responses.
         */
        JobPublic: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Code */
            job_code: string | null;
            /** Job Name */
            job_name: string;
            /** Site Address */
            site_address: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst: string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
        };
        /**
         * JobStatus
         * @description Lifecycle state of a :class:`Job`.
         *
         *     ``active`` jobs accept new expenses; ``completed`` jobs are read-only
         *     in Phase 1 (no separate archival flow is needed for V1).
         * @enum {string}
         */
        JobStatus: "active" | "completed";
        /**
         * JobUpdate
         * @description Body of ``PATCH /jobs/{job_id}`` (admin-only).
         */
        JobUpdate: {
            /** Job Name */
            job_name?: string | null;
            /** Job Code */
            job_code?: string | null;
            /** Site Address */
            site_address?: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst?: number | string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst?: number | string | null;
            status?: components["schemas"]["JobStatus"] | null;
        };
        /**
         * JobWithDetailPublic
         * @description Full serialised job including aliases + category budgets.
         *
         *     Returned by ``GET /jobs/{job_id}`` only — list responses stay
         *     compact via ``JobPublic``.
         */
        JobWithDetailPublic: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Code */
            job_code: string | null;
            /** Job Name */
            job_name: string;
            /** Site Address */
            site_address: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst: string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Aliases
             * @default []
             */
            aliases: components["schemas"]["JobAliasPublic"][];
            /**
             * Category Budgets
             * @default []
             */
            category_budgets: components["schemas"]["JobCategoryBudgetPublic"][];
        };
        /**
         * LanguageCode
         * @description Allowed UI language preferences.
         * @enum {string}
         */
        LanguageCode: "en" | "zh";
        /**
         * LoginRequest
         * @description Credentials submitted to ``POST /auth/login``.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * RefreshRequest
         * @description Body of ``POST /auth/refresh``.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * TokenPair
         * @description Access + refresh pair returned on successful login.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserInvite
         * @description Request body for ``POST /users/invite`` (admin only).
         *
         *     The admin supplies ``initial_password`` directly in Phase 1.
         *     No password-strength rules are applied here — that lands in
         *     Phase 6 alongside email-based reset.
         */
        UserInvite: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Initial Password */
            initial_password: string;
            /** @default en */
            language_preference: components["schemas"]["LanguageCode"];
        };
        /**
         * UserPublic
         * @description Serialised view of a ``User`` safe to return over the wire.
         */
        UserPublic: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            language_preference: components["schemas"]["LanguageCode"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @description Allowed roles on a SiteTracker user account.
         * @enum {string}
         */
        UserRole: "admin" | "contributor";
        /**
         * UserUpdate
         * @description Request body for ``PATCH /users/{user_id}`` (admin only).
         *
         *     All fields are optional; only those supplied are mutated. ``None``
         *     means "do not change". Setting ``is_active=False`` deactivates the
         *     user; their existing access tokens immediately stop working because
         *     ``get_current_user`` requires ``is_active``.
         */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
            language_preference?: components["schemas"]["LanguageCode"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: {
                /** @description Admin-only toggle: include archived (is_active=false) rows in the response. Default False — the V1 dashboard hides them. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"][];
                };
            };
        };
    };
    create_job_endpoint_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobWithDetailPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_endpoint_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alias_endpoint_jobs__job_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAliasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAliasPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_category_budget_endpoint_jobs__job_id__category_budgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCategoryBudgetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCategoryBudgetPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_endpoint_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
        };
    };
    invite_user_endpoint_users_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_endpoint_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
