/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email + password for an access/refresh token pair.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the user identified by the bearer access token.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Issue a new access token given a valid, unexpired refresh token.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Stateless logout: the server does not (yet) revoke anything.
         *
         *     Phase 6 will add a ``jti`` blacklist check here so tokens issued
         *     before logout stop being accepted for the remainder of their TTL.
         *     Until then, clients simply discard their stored tokens.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List categories ordered by ``display_order``.
         */
        get: operations["list_categories_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description Create a category (admin only).
         */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Category
         * @description Partially update a category (admin only).
         */
        patch: operations["update_category_categories__category_id__patch"];
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Expenses Endpoint
         * @description List expenses (contributors are restricted to their own rows).
         */
        get: operations["list_expenses_endpoint_expenses_get"];
        put?: never;
        /**
         * Create Expense Endpoint
         * @description Create an expense from raw text or structured fields.
         *
         *     The service runs the parser when ``raw_input_text`` is supplied
         *     and merges any explicit structured overrides on top of the parser
         *     draft (structured wins).
         */
        post: operations["create_expense_endpoint_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Parse Endpoint
         * @description Run the parser and return draft + diagnostics. Does not persist.
         */
        post: operations["preview_parse_endpoint_expenses_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense Endpoint
         * @description Fetch a single expense with nested supplier + category.
         */
        get: operations["get_expense_endpoint_expenses__expense_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Expense Endpoint
         * @description Admin-only soft delete: sets review_status=rejected + audits.
         */
        delete: operations["delete_expense_endpoint_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Expense Endpoint
         * @description Partial update with RBAC + audit rules enforced in the service.
         */
        patch: operations["update_expense_endpoint_expenses__expense_id__patch"];
        trace?: never;
    };
    "/expenses/{expense_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Endpoint
         * @description Admin-only audit trail, newest first.
         */
        get: operations["get_audit_endpoint_expenses__expense_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs Endpoint
         * @description List all jobs (any authenticated caller).
         *
         *     Phase 3 Lite: each row carries a ``summary`` field with the per-job
         *     ex-GST aggregates used by the dashboard. The summary is populated
         *     for every row — jobs with no expenses get an all-zero summary so
         *     the UI never has to special-case missing data. The auth posture is
         *     unchanged from Phase 1 (any authenticated user can list jobs); the
         *     dashboard surface that consumes ``summary`` is admin-only by route
         *     composition (admin nav), not by route auth.
         */
        get: operations["list_jobs_endpoint_jobs_get"];
        put?: never;
        /**
         * Create Job Endpoint
         * @description Create a job (admin only).
         */
        post: operations["create_job_endpoint_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Endpoint
         * @description Fetch a job with its aliases + category budgets eager-loaded.
         */
        get: operations["get_job_endpoint_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Job Endpoint
         * @description Partially update a job (admin only).
         */
        patch: operations["update_job_endpoint_jobs__job_id__patch"];
        trace?: never;
    };
    "/jobs/{job_id}/budget-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Budget Summary Endpoint
         * @description Per-job actual-vs-budget rollup with per-category breakdown (admin only).
         *
         *     Phase 3 Lite. The categories list includes every category with
         *     either a budget row or at least one non-rejected expense on the
         *     job; categories with neither are omitted.
         */
        get: operations["get_job_budget_summary_endpoint_jobs__job_id__budget_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Alias Endpoint
         * @description Attach an alias to a job (admin only).
         *
         *     409 on a duplicate normalised alias (globally unique — see the
         *     ``JobAlias`` model's uniqueness contract).
         */
        post: operations["add_alias_endpoint_jobs__job_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/category-budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Category Budget Endpoint
         * @description Attach a per-category budget row to a job (admin only).
         *
         *     404 if either the job or the category doesn't exist. 409 on a
         *     duplicate ``(job_id, category_id)`` pair.
         */
        post: operations["add_category_budget_endpoint_jobs__job_id__category_budgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Queue
         * @description List queue rows ordered by ``opened_at`` ASC (admin-only).
         *
         *     The ``status`` query param is aliased onto a Python-safe
         *     ``status_filter`` parameter name to avoid shadowing
         *     :mod:`fastapi.status`.
         */
        get: operations["list_queue_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue Detail
         * @description Return the queue row + nested expense + duplicate-of expense (admin-only).
         */
        get: operations["get_queue_detail_review_queue__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{review_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Queue
         * @description Approve a queue entry (admin-only).
         *
         *     The service runs the expense-update + queue-close + audit-write
         *     inside the single request-scoped transaction ``get_db`` owns. Any
         *     failure rolls back the whole unit; on success they all commit.
         */
        post: operations["resolve_queue_review_queue__review_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{review_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Queue
         * @description Reject a queue entry (admin-only). Atomic like :func:`resolve_queue`.
         */
        post: operations["reject_queue_review_queue__review_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Suppliers Endpoint
         * @description List all suppliers (any authenticated caller).
         *
         *     With ``?active_only=1`` only ``is_active=True`` rows are returned.
         */
        get: operations["list_suppliers_endpoint_suppliers_get"];
        put?: never;
        /**
         * Create Supplier Endpoint
         * @description Create a supplier (admin only).
         */
        post: operations["create_supplier_endpoint_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Supplier Endpoint
         * @description Partially update a supplier (admin only).
         */
        patch: operations["update_supplier_endpoint_suppliers__supplier_id__patch"];
        trace?: never;
    };
    "/suppliers/{supplier_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Alias Endpoint
         * @description Attach an alias to a supplier (admin only).
         *
         *     409 on a duplicate normalised alias (globally unique — see the
         *     ``SupplierAlias`` model's uniqueness contract).
         */
        post: operations["add_alias_endpoint_suppliers__supplier_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users Endpoint
         * @description Return every user. Admin only.
         */
        get: operations["list_users_endpoint_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite User Endpoint
         * @description Create a user from an admin-supplied ``initial_password``.
         *
         *     Phase 1 has no email delivery; the admin is expected to communicate
         *     the password to the invitee out of band. Phase 6 will add a proper
         *     magic-link / reset-password flow.
         *
         *     Returns 201 with the new :class:`UserPublic`. A pre-existing user
         *     with the same email produces a 409.
         */
        post: operations["invite_user_endpoint_users_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Endpoint
         * @description Partially update a user. Admin only.
         *
         *     Any subset of ``full_name``, ``role``, ``is_active``, and
         *     ``language_preference`` may be supplied. Setting ``is_active=False``
         *     forces the target's existing access tokens to 401 on the next auth
         *     check — :func:`app.deps.get_current_user` rejects deactivated users.
         */
        patch: operations["update_user_endpoint_users__user_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessToken
         * @description Single-token response returned by ``POST /auth/refresh``.
         */
        AccessToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * AuditRow
         * @description Wire shape of a single :class:`ExpenseAuditLog` row.
         */
        AuditRow: {
            /**
             * Audit Id
             * Format: uuid
             */
            audit_id: string;
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /**
             * Edited By User Id
             * Format: uuid
             */
            edited_by_user_id: string;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
            /** Changed Fields */
            changed_fields: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string | null;
        };
        /**
         * CategoryBudgetRow
         * @description One row in the per-category breakdown on ``/jobs/{id}/budget-summary``.
         *
         *     ``budget_ex_gst`` and ``remaining_ex_gst`` are ``None`` when there is
         *     no ``job_category_budgets`` row for this category — the UI renders
         *     "—" and a `No budget` chip.
         */
        CategoryBudgetRow: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Actual Ex Gst */
            actual_ex_gst: string;
            /** Budget Ex Gst */
            budget_ex_gst: string | null;
            /** Remaining Ex Gst */
            remaining_ex_gst: string | null;
            /** Overspend */
            overspend: boolean;
        };
        /**
         * CategoryCreate
         * @description Body of ``POST /categories`` (admin-only).
         */
        CategoryCreate: {
            /** Category Name */
            category_name: string;
            /** Display Order */
            display_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * CategoryPublic
         * @description Serialised view of a :class:`~app.models.category.Category` row.
         */
        CategoryPublic: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Display Order */
            display_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * CategoryUpdate
         * @description Body of ``PATCH /categories/{category_id}`` (admin-only).
         */
        CategoryUpdate: {
            /** Category Name */
            category_name?: string | null;
            /** Display Order */
            display_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * ExpenseCreate
         * @description Body of ``POST /expenses`` and the draft carrier in ``ParsePreview``.
         *
         *     Two submission modes are supported:
         *
         *     * **raw_input_text mode** — the caller passes only
         *       ``raw_input_text`` (plus optional overrides) and the service
         *       layer runs the parser first, merging any explicitly-set
         *       structured fields on top of the parser's draft.
         *     * **structured mode** — the caller supplies all the required
         *       structured fields (``job_id``, ``amount_inc_gst``, etc.) and
         *       ``raw_input_text`` is omitted; the parser is NOT invoked.
         *
         *     Validation of required fields (amount, job, supplier-or-description
         *     for supplier expenses, date sanity) is performed in the service.
         */
        "ExpenseCreate-Input": {
            /** Raw Input Text */
            raw_input_text?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** @default supplier_expense */
            expense_type: components["schemas"]["ExpenseType"];
            /** Amount Inc Gst */
            amount_inc_gst?: number | string | null;
            /** Amount Ex Gst */
            amount_ex_gst?: number | string | null;
            /** Gst Amount */
            gst_amount?: number | string | null;
            /** @default unknown */
            payment_method: components["schemas"]["PaymentMethod"];
            /** Expense Date */
            expense_date?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /** @default no_receipt */
            receipt_status: components["schemas"]["ReceiptStatus"];
        };
        /**
         * ExpenseCreate
         * @description Body of ``POST /expenses`` and the draft carrier in ``ParsePreview``.
         *
         *     Two submission modes are supported:
         *
         *     * **raw_input_text mode** — the caller passes only
         *       ``raw_input_text`` (plus optional overrides) and the service
         *       layer runs the parser first, merging any explicitly-set
         *       structured fields on top of the parser's draft.
         *     * **structured mode** — the caller supplies all the required
         *       structured fields (``job_id``, ``amount_inc_gst``, etc.) and
         *       ``raw_input_text`` is omitted; the parser is NOT invoked.
         *
         *     Validation of required fields (amount, job, supplier-or-description
         *     for supplier expenses, date sanity) is performed in the service.
         */
        "ExpenseCreate-Output": {
            /** Raw Input Text */
            raw_input_text?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** @default supplier_expense */
            expense_type: components["schemas"]["ExpenseType"];
            /** Amount Inc Gst */
            amount_inc_gst?: string | null;
            /** Amount Ex Gst */
            amount_ex_gst?: string | null;
            /** Gst Amount */
            gst_amount?: string | null;
            /** @default unknown */
            payment_method: components["schemas"]["PaymentMethod"];
            /** Expense Date */
            expense_date?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /** @default no_receipt */
            receipt_status: components["schemas"]["ReceiptStatus"];
        };
        /**
         * ExpenseCreateResponse
         * @description Body of ``POST /expenses`` 201 response.
         *
         *     Carries the persisted :class:`ExpensePublic` plus an optional
         *     :class:`ParseDiagnostics` block — populated iff
         *     ``raw_input_text`` drove the create. Structured-only submissions
         *     return ``parse=None``.
         */
        ExpenseCreateResponse: {
            expense: components["schemas"]["ExpensePublic"];
            parse?: components["schemas"]["ParseDiagnostics"] | null;
        };
        /**
         * ExpenseDetailPublic
         * @description Body of ``GET /expenses/{id}`` — adds nested supplier + category.
         */
        ExpenseDetailPublic: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Supplier Id */
            supplier_id: string | null;
            /**
             * Entered By User Id
             * Format: uuid
             */
            entered_by_user_id: string;
            expense_type: components["schemas"]["ExpenseType"];
            /** Raw Input Text */
            raw_input_text: string | null;
            /** Description */
            description: string | null;
            /** Amount Inc Gst */
            amount_inc_gst: string;
            /** Amount Ex Gst */
            amount_ex_gst: string;
            /** Gst Amount */
            gst_amount: string;
            payment_method: components["schemas"]["PaymentMethod"];
            /**
             * Expense Date
             * Format: date
             */
            expense_date: string;
            /** Category Id */
            category_id: string | null;
            review_status: components["schemas"]["ReviewStatus"];
            receipt_status: components["schemas"]["ReceiptStatus"];
            /** Confidence Score */
            confidence_score: string | null;
            /** Duplicate Flag */
            duplicate_flag: boolean;
            /** Duplicate Of Expense Id */
            duplicate_of_expense_id: string | null;
            /** Notes */
            notes: string | null;
            supplier: components["schemas"]["SupplierPublic"] | null;
            category: components["schemas"]["CategoryPublic"] | null;
        };
        /**
         * ExpenseListResponse
         * @description Body of ``GET /expenses``. Supports cursor-style pagination.
         */
        ExpenseListResponse: {
            /** Items */
            items: components["schemas"]["ExpensePublic"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ExpensePublic
         * @description Compact expense wire shape for list + post-create + post-patch.
         */
        ExpensePublic: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Supplier Id */
            supplier_id: string | null;
            /**
             * Entered By User Id
             * Format: uuid
             */
            entered_by_user_id: string;
            expense_type: components["schemas"]["ExpenseType"];
            /** Raw Input Text */
            raw_input_text: string | null;
            /** Description */
            description: string | null;
            /** Amount Inc Gst */
            amount_inc_gst: string;
            /** Amount Ex Gst */
            amount_ex_gst: string;
            /** Gst Amount */
            gst_amount: string;
            payment_method: components["schemas"]["PaymentMethod"];
            /**
             * Expense Date
             * Format: date
             */
            expense_date: string;
            /** Category Id */
            category_id: string | null;
            review_status: components["schemas"]["ReviewStatus"];
            receipt_status: components["schemas"]["ReceiptStatus"];
            /** Confidence Score */
            confidence_score: string | null;
            /** Duplicate Flag */
            duplicate_flag: boolean;
            /** Duplicate Of Expense Id */
            duplicate_of_expense_id: string | null;
            /** Notes */
            notes: string | null;
        };
        /**
         * ExpenseType
         * @description What kind of money-movement this expense represents.
         * @enum {string}
         */
        ExpenseType: "supplier_expense" | "labour" | "adjustment";
        /**
         * ExpenseUpdate
         * @description Body of ``PATCH /expenses/{id}``. Every field optional.
         *
         *     ``reason`` is an out-of-band audit note for admin edits on reviewed
         *     rows — it is NOT written back as a column on the expense.
         */
        ExpenseUpdate: {
            /** Supplier Id */
            supplier_id?: string | null;
            expense_type?: components["schemas"]["ExpenseType"] | null;
            /** Amount Inc Gst */
            amount_inc_gst?: number | string | null;
            /** Amount Ex Gst */
            amount_ex_gst?: number | string | null;
            /** Gst Amount */
            gst_amount?: number | string | null;
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            /** Expense Date */
            expense_date?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            receipt_status?: components["schemas"]["ReceiptStatus"] | null;
            review_status?: components["schemas"]["ReviewStatus"] | null;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobAliasCreate
         * @description Body of ``POST /jobs/{job_id}/aliases`` (admin-only).
         */
        JobAliasCreate: {
            /** Alias Text */
            alias_text: string;
            language_code?: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * JobAliasPublic
         * @description Serialised view of a :class:`~app.models.job.JobAlias`.
         */
        JobAliasPublic: {
            /**
             * Alias Id
             * Format: uuid
             */
            alias_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Alias Text */
            alias_text: string;
            /** Alias Text Normalized */
            alias_text_normalized: string;
            language_code: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * JobBudgetSummary
         * @description Full envelope for ``GET /jobs/{job_id}/budget-summary`` (admin-only).
         *
         *     Per-job totals (matching :class:`JobSummary`) plus the union of
         *     categories with either a budget row or at least one non-rejected
         *     expense. Categories with neither are omitted (no zero-zero rows).
         *
         *     Phase 3 Lite+ extends with five derived margin fields plus the two
         *     effective threshold fields. All of the margin fields are nullable
         *     and computed only when the inputs allow — see the nullable-rules
         *     table in ``docs/phase-3-lite-plus-plan.md``. Specifically:
         *
         *     * ``target_cost_limit_ex_gst`` requires contract + target
         *     * ``budgeted_profit_ex_gst`` requires contract + total_budget
         *     * ``budgeted_profit_ratio_pct`` requires contract (and contract > 0)
         *       + total_budget
         *     * ``budget_delta_vs_target_cost_ex_gst`` requires all three of
         *       contract + target + total_budget
         *
         *     There is intentionally **no** ``actual_profit_*`` field. Mid-project
         *     actual profit is not knowable (future costs aren't included). The
         *     UI may surface ``contract − cost_to_date`` as a low-emphasis
         *     contextual line labelled "Remaining contract value after costs to
         *     date" with an explicit "not actual profit" disclaimer; that
         *     presentation rule is documented in the plan and enforced by the
         *     frontend, not by this schema.
         */
        JobBudgetSummary: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Actual Inc Gst */
            actual_inc_gst: string;
            /** Actual Ex Gst */
            actual_ex_gst: string;
            /** Gst Amount */
            gst_amount: string;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            /** Remaining Ex Gst */
            remaining_ex_gst: string | null;
            /** Percent Consumed */
            percent_consumed: string | null;
            /** Overspend */
            overspend: boolean;
            /** Target Profit Ratio Pct */
            target_profit_ratio_pct: string | null;
            /** Target Cost Limit Ex Gst */
            target_cost_limit_ex_gst: string | null;
            /** Budgeted Profit Ex Gst */
            budgeted_profit_ex_gst: string | null;
            /** Budgeted Profit Ratio Pct */
            budgeted_profit_ratio_pct: string | null;
            /** Budget Delta Vs Target Cost Ex Gst */
            budget_delta_vs_target_cost_ex_gst: string | null;
            /** Effective Warning Amber Pct */
            effective_warning_amber_pct: string;
            /** Effective Warning Red Pct */
            effective_warning_red_pct: string;
            /** Categories */
            categories: components["schemas"]["CategoryBudgetRow"][];
        };
        /**
         * JobCategoryBudgetCreate
         * @description Body of ``POST /jobs/{job_id}/category-budgets`` (admin-only).
         */
        JobCategoryBudgetCreate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Budget Amount Ex Gst */
            budget_amount_ex_gst: number | string;
        };
        /**
         * JobCategoryBudgetPublic
         * @description Serialised view of a :class:`~app.models.job.JobCategoryBudget`.
         *
         *     The nested ``category`` is eager-loaded via the ``lazy="joined"``
         *     relationship on the model, so the HTTP response always carries the
         *     category's public shape inline — no extra round trip.
         */
        JobCategoryBudgetPublic: {
            /**
             * Budget Id
             * Format: uuid
             */
            budget_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Budget Amount Ex Gst */
            budget_amount_ex_gst: string;
            category: components["schemas"]["CategoryPublic"];
        };
        /**
         * JobCreate
         * @description Body of ``POST /jobs`` (admin-only).
         *
         *     Phase 3 Lite+ adds three optional percent fields. All three are
         *     enforced by both Pydantic (here) and DB CHECK constraints (see
         *     ``backend/app/models/job.py`` and migration ``b3e7a8f1c042``).
         */
        JobCreate: {
            /** Job Name */
            job_name: string;
            /** Job Code */
            job_code?: string | null;
            /** Site Address */
            site_address?: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst?: number | string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst?: number | string | null;
            /** Target Profit Ratio Pct */
            target_profit_ratio_pct?: number | string | null;
            /** Warning Amber Pct */
            warning_amber_pct?: number | string | null;
            /** Warning Red Pct */
            warning_red_pct?: number | string | null;
            /** @default active */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobPublic
         * @description Compact serialised view of a :class:`~app.models.job.Job`.
         *
         *     Used by ``GET /jobs`` (list) and by non-detail POST/PATCH responses.
         *
         *     The optional ``summary`` field is populated by ``GET /jobs`` (Phase 3
         *     Lite) so the list page can render budget visibility per row without a
         *     second round trip. Create/update responses leave it ``None``: those
         *     are write-action results, not snapshots, and the cost of a one-off
         *     aggregation on every write is not justified by the dashboard need.
         */
        JobPublic: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Code */
            job_code: string | null;
            /** Job Name */
            job_name: string;
            /** Site Address */
            site_address: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst: string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            /** Target Profit Ratio Pct */
            target_profit_ratio_pct?: string | null;
            /** Warning Amber Pct */
            warning_amber_pct?: string | null;
            /** Warning Red Pct */
            warning_red_pct?: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            summary?: components["schemas"]["JobSummary"] | null;
        };
        /**
         * JobStatus
         * @description Lifecycle state of a :class:`Job`.
         *
         *     ``active`` jobs accept new expenses; ``completed`` jobs are read-only
         *     in Phase 1 (no separate archival flow is needed for V1).
         * @enum {string}
         */
        JobStatus: "active" | "completed";
        /**
         * JobSummary
         * @description Per-job aggregate; embedded in :class:`JobPublic` on ``GET /jobs``.
         *
         *     ``remaining_ex_gst`` and ``percent_consumed`` are ``None`` when no
         *     budget is set (NULL or zero). ``overspend`` is always a bool — it
         *     is ``False`` (not ``None``) when no budget is set so the UI never
         *     has to handle a tri-state for the chip.
         *
         *     Phase 3 Lite+ adds the two ``effective_warning_*_pct`` fields. They
         *     are **always** populated — either the per-job stored override (from
         *     ``JobPublic.warning_*_pct``) or the system default (80.00 / 100.00).
         *     The stored fields stay nullable on ``JobPublic``; the effective
         *     fields here are what the chip-banding logic on the frontend
         *     consumes. This separation is point 3 of the operator review
         *     (2026-05-10): never overwrite a NULL stored value with a default.
         */
        JobSummary: {
            /** Actual Inc Gst */
            actual_inc_gst: string;
            /** Actual Ex Gst */
            actual_ex_gst: string;
            /** Gst Amount */
            gst_amount: string;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            /** Remaining Ex Gst */
            remaining_ex_gst: string | null;
            /** Percent Consumed */
            percent_consumed: string | null;
            /** Overspend */
            overspend: boolean;
            /** Effective Warning Amber Pct */
            effective_warning_amber_pct: string;
            /** Effective Warning Red Pct */
            effective_warning_red_pct: string;
        };
        /**
         * JobUpdate
         * @description Body of ``PATCH /jobs/{job_id}`` (admin-only).
         *
         *     Phase 3 Lite+ extends with the same three optional percent fields
         *     as ``JobCreate``. The cross-field amber-lt-red check still applies
         *     on PATCH; if only one of (amber, red) is supplied, it must still
         *     be coherent with whatever the row already holds — that combined
         *     check is enforced server-side by the DB CHECK constraint after the
         *     update is applied (Pydantic only sees the patch payload).
         */
        JobUpdate: {
            /** Job Name */
            job_name?: string | null;
            /** Job Code */
            job_code?: string | null;
            /** Site Address */
            site_address?: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst?: number | string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst?: number | string | null;
            /** Target Profit Ratio Pct */
            target_profit_ratio_pct?: number | string | null;
            /** Warning Amber Pct */
            warning_amber_pct?: number | string | null;
            /** Warning Red Pct */
            warning_red_pct?: number | string | null;
            status?: components["schemas"]["JobStatus"] | null;
        };
        /**
         * JobWithDetailPublic
         * @description Full serialised job including aliases + category budgets.
         *
         *     Returned by ``GET /jobs/{job_id}`` only — list responses stay
         *     compact via ``JobPublic``.
         */
        JobWithDetailPublic: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Code */
            job_code: string | null;
            /** Job Name */
            job_name: string;
            /** Site Address */
            site_address: string | null;
            /** Contract Value Ex Gst */
            contract_value_ex_gst: string | null;
            /** Total Budget Ex Gst */
            total_budget_ex_gst: string | null;
            /** Target Profit Ratio Pct */
            target_profit_ratio_pct?: string | null;
            /** Warning Amber Pct */
            warning_amber_pct?: string | null;
            /** Warning Red Pct */
            warning_red_pct?: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            summary?: components["schemas"]["JobSummary"] | null;
            /**
             * Aliases
             * @default []
             */
            aliases: components["schemas"]["JobAliasPublic"][];
            /**
             * Category Budgets
             * @default []
             */
            category_budgets: components["schemas"]["JobCategoryBudgetPublic"][];
        };
        /**
         * LanguageCode
         * @description Allowed UI language preferences.
         * @enum {string}
         */
        LanguageCode: "en" | "zh";
        /**
         * LoginRequest
         * @description Credentials submitted to ``POST /auth/login``.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ParseDiagnostics
         * @description Subset of the parser's ``ParseResult`` exposed to API clients.
         *
         *     Includes per-stage confidences, the derived review reason codes,
         *     ambiguity tuples, the ``matched_via`` labels, the candidate
         *     supplier proposal, the duplicate-of pointer, and the per-field
         *     source map (``{"amount": "rules", "job": "rules", ...}``) so the
         *     UI can render "which fields did rules populate vs LLM".
         */
        ParseDiagnostics: {
            /** Amount Conf */
            amount_conf: number;
            /** Job Conf */
            job_conf: number;
            /** Supplier Conf */
            supplier_conf: number;
            /** Category Conf */
            category_conf: number;
            /** Unsupported Currency */
            unsupported_currency: boolean;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReviewReasonCode"][];
            /** Ambiguous Job Matches */
            ambiguous_job_matches: string[];
            /** Ambiguous Supplier Matches */
            ambiguous_supplier_matches: string[];
            /** Matched Job Via */
            matched_job_via: string | null;
            /** Matched Supplier Via */
            matched_supplier_via: string | null;
            /** Candidate Supplier Name */
            candidate_supplier_name: string | null;
            /** Duplicate Of Expense Id */
            duplicate_of_expense_id: string | null;
            /** Source Per Field */
            source_per_field: {
                [key: string]: string;
            };
        };
        /**
         * ParsePreview
         * @description Body of ``POST /expenses/parse`` 200 response.
         *
         *     Does NOT persist anything: returns the parser's best-guess
         *     :class:`ExpenseCreate` draft together with the diagnostics block
         *     so the UI can show confidences + review reasons before the user
         *     commits with ``POST /expenses``.
         */
        ParsePreview: {
            draft: components["schemas"]["ExpenseCreate-Output"];
            diagnostics: components["schemas"]["ParseDiagnostics"];
        };
        /**
         * ParsePreviewRequest
         * @description Body of ``POST /expenses/parse``.
         *
         *     A minimal request shape that does not force the caller to supply
         *     every :class:`ExpenseCreate` field. Only ``raw_input_text`` is
         *     required; ``expense_date`` defaults to today in the service and
         *     ``expense_type`` defaults to :attr:`ExpenseType.supplier_expense`.
         */
        ParsePreviewRequest: {
            /** Raw Input Text */
            raw_input_text: string;
            /** Expense Date */
            expense_date?: string | null;
            /** @default supplier_expense */
            expense_type: components["schemas"]["ExpenseType"];
        };
        /**
         * PaymentMethod
         * @description How the expense was settled.
         *
         *     ``unknown`` is the default because the Phase 2 parser often cannot
         *     determine the payment method from free text.
         * @enum {string}
         */
        PaymentMethod: "cash" | "transfer" | "unknown";
        /**
         * ReceiptStatus
         * @description Lifecycle of the physical / digital receipt for this expense.
         *
         *     Phase 2 has only two values — ``no_receipt`` (default, nothing on
         *     file) and ``expected_later`` (admin flagged that a receipt will be
         *     supplied later). A third "attached" value is introduced in Phase 5
         *     when the receipt upload flow goes live; it must NOT be added here.
         * @enum {string}
         */
        ReceiptStatus: "no_receipt" | "expected_later";
        /**
         * RefreshRequest
         * @description Body of ``POST /auth/refresh``.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RejectRequest
         * @description Payload for ``POST /review-queue/{id}/reject``.
         *
         *     ``notes`` is stored on the queue row and included in the audit log.
         */
        RejectRequest: {
            /** Notes */
            notes?: string | null;
        };
        /**
         * ResolveRequest
         * @description Payload for ``POST /review-queue/{id}/resolve``.
         *
         *     ``expense_patch`` (optional) lets the admin update any expense
         *     fields while approving; it's applied before the status flips to
         *     reviewed. ``notes`` is stored on the queue row and included in the
         *     audit log if present.
         */
        ResolveRequest: {
            expense_patch?: components["schemas"]["ExpenseUpdate"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ReviewQueueDetail
         * @description Detail shape for ``GET /review-queue/{id}``.
         *
         *     Bundles the queue row, the expense being reviewed, and — when the
         *     queue entry was created because of a duplicate suspicion — the
         *     earlier expense that produced the flag. Ambiguous-match metadata
         *     is not persisted and thus not surfaced here.
         */
        ReviewQueueDetail: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReviewReasonCode"][];
            status: components["schemas"]["ReviewQueueStatus"];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved By User Id */
            resolved_by_user_id: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolution Notes */
            resolution_notes: string | null;
            expense: components["schemas"]["ExpenseDetailPublic"];
            duplicate_of: components["schemas"]["ExpenseDetailPublic"] | null;
        };
        /**
         * ReviewQueuePublic
         * @description Summary shape for ``GET /review-queue`` list view.
         */
        ReviewQueuePublic: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReviewReasonCode"][];
            status: components["schemas"]["ReviewQueueStatus"];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved By User Id */
            resolved_by_user_id: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolution Notes */
            resolution_notes: string | null;
        };
        /**
         * ReviewQueueStatus
         * @description Lifecycle of a queued review.
         * @enum {string}
         */
        ReviewQueueStatus: "open" | "resolved" | "rejected";
        /**
         * ReviewReasonCode
         * @description Why an expense landed in the review queue.
         *
         *     The declaration order is canonical — the UI renders reason chips
         *     in exactly this order. Do not reorder without a plan-level change.
         * @enum {string}
         */
        ReviewReasonCode: "job_uncertain" | "supplier_uncertain" | "category_uncertain" | "amount_uncertain" | "duplicate_suspected" | "unsupported_currency";
        /**
         * ReviewStatus
         * @description Admin review verdict on an expense row.
         * @enum {string}
         */
        ReviewStatus: "pending" | "reviewed" | "rejected";
        /**
         * SupplierAliasCreate
         * @description Body of ``POST /suppliers/{supplier_id}/aliases`` (admin-only).
         */
        SupplierAliasCreate: {
            /** Alias Text */
            alias_text: string;
            language_code?: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * SupplierAliasPublic
         * @description Serialised view of a :class:`~app.models.supplier.SupplierAlias`.
         */
        SupplierAliasPublic: {
            /**
             * Alias Id
             * Format: uuid
             */
            alias_id: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Alias Text */
            alias_text: string;
            /** Alias Text Normalized */
            alias_text_normalized: string;
            language_code: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * SupplierCreate
         * @description Body of ``POST /suppliers`` (admin-only).
         */
        SupplierCreate: {
            /** Supplier Name */
            supplier_name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * SupplierPublic
         * @description Serialised view of a :class:`~app.models.supplier.Supplier` row.
         */
        SupplierPublic: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /** Supplier Name */
            supplier_name: string;
            /** Supplier Normalized */
            supplier_normalized: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * SupplierUpdate
         * @description Body of ``PATCH /suppliers/{supplier_id}`` (admin-only).
         */
        SupplierUpdate: {
            /** Supplier Name */
            supplier_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * TokenPair
         * @description Access + refresh pair returned on successful login.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserInvite
         * @description Request body for ``POST /users/invite`` (admin only).
         *
         *     The admin supplies ``initial_password`` directly in Phase 1.
         *     No password-strength rules are applied here — that lands in
         *     Phase 6 alongside email-based reset.
         */
        UserInvite: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Initial Password */
            initial_password: string;
            /** @default en */
            language_preference: components["schemas"]["LanguageCode"];
        };
        /**
         * UserPublic
         * @description Serialised view of a ``User`` safe to return over the wire.
         */
        UserPublic: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            language_preference: components["schemas"]["LanguageCode"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @description Allowed roles on a SiteTracker user account.
         * @enum {string}
         */
        UserRole: "admin" | "contributor";
        /**
         * UserUpdate
         * @description Request body for ``PATCH /users/{user_id}`` (admin only).
         *
         *     All fields are optional; only those supplied are mutated. ``None``
         *     means "do not change". Setting ``is_active=False`` deactivates the
         *     user; their existing access tokens immediately stop working because
         *     ``get_current_user`` requires ``is_active``.
         */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
            language_preference?: components["schemas"]["LanguageCode"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: {
                /** @description Admin-only toggle: include archived (is_active=false) rows in the response. Default False — the V1 dashboard hides them. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_endpoint_expenses_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                status?: components["schemas"]["ReviewStatus"] | null;
                mine?: number;
                from?: string | null;
                to?: string | null;
                receipt_status?: components["schemas"]["ReceiptStatus"] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_endpoint_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_parse_endpoint_expenses_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParsePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_endpoint_expenses__expense_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseDetailPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_endpoint_expenses__expense_id__delete: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_endpoint_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpensePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_endpoint_expenses__expense_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"][];
                };
            };
        };
    };
    create_job_endpoint_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobWithDetailPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_endpoint_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_budget_summary_endpoint_jobs__job_id__budget_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobBudgetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alias_endpoint_jobs__job_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAliasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAliasPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_category_budget_endpoint_jobs__job_id__category_budgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCategoryBudgetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCategoryBudgetPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queue_review_queue_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReviewQueueStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_detail_review_queue__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_queue_review_queue__review_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_queue_review_queue__review_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_endpoint_suppliers_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_endpoint_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_endpoint_suppliers__supplier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alias_endpoint_suppliers__supplier_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierAliasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierAliasPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_endpoint_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
        };
    };
    invite_user_endpoint_users_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_endpoint_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
