"""add suppliers

Revision ID: 3324509be140
Revises: cbd2c5157346
Create Date: 2026-04-22 19:25:29.927730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3324509be140"
down_revision: Union[str, Sequence[str], None] = "cbd2c5157346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=False),
        sa.Column("supplier_normalized", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("supplier_id"),
        sa.UniqueConstraint("supplier_normalized", name="uq_suppliers_supplier_normalized"),
    )
    op.create_table(
        "supplier_aliases",
        sa.Column("alias_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("alias_text", sa.String(length=255), nullable=False),
        sa.Column("alias_text_normalized", sa.String(length=255), nullable=False),
        # ``language_code`` already exists as a Postgres ENUM type (owned by
        # the users migration). ``create_type=False`` tells SQLAlchemy not
        # to re-emit ``CREATE TYPE language_code`` here.
        sa.Column(
            "language_code",
            postgresql.ENUM("en", "zh", name="language_code", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.supplier_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("alias_text_normalized", name="uq_supplier_aliases_alias_normalized"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplier_aliases")
    op.drop_table("suppliers")
    # ``language_code`` is owned by the users migration and is intentionally
    # NOT dropped here — the jobs migration also reuses it.
    # ### end Alembic commands ###
