"""add expenses

Revision ID: 82593095cdf2
Revises: 3324509be140
Create Date: 2026-04-22 19:33:26.071315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "82593095cdf2"
down_revision: Union[str, Sequence[str], None] = "3324509be140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("entered_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "expense_type",
            sa.Enum("supplier_expense", "labour", "adjustment", name="expense_type"),
            server_default="supplier_expense",
            nullable=False,
        ),
        sa.Column("raw_input_text", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("amount_inc_gst", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_ex_gst", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gst_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("cash", "transfer", "unknown", name="payment_method"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("pending", "reviewed", "rejected", name="review_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "receipt_status",
            sa.Enum("no_receipt", "expected_later", name="receipt_status"),
            server_default="no_receipt",
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("duplicate_flag", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("duplicate_of_expense_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_expense_id"],
            ["expenses.expense_id"],
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
        ),
        sa.PrimaryKeyConstraint("expense_id"),
    )
    op.create_index("ix_expenses_category_id", "expenses", ["category_id"], unique=False)
    op.create_index(
        "ix_expenses_entered_by_user_id", "expenses", ["entered_by_user_id"], unique=False
    )
    op.create_index(
        "ix_expenses_job_id_expense_date",
        "expenses",
        ["job_id", "expense_date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index("ix_expenses_review_status", "expenses", ["review_status"], unique=False)
    op.create_index("ix_expenses_supplier_id", "expenses", ["supplier_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Dropping the table drops its indexes automatically in Postgres, so
    # no explicit ``drop_index`` calls are needed.
    op.drop_table("expenses")
    # Autogenerate does not drop the Postgres ENUM types created alongside
    # the ``expenses`` table; drop them explicitly so a downgrade + upgrade
    # round-trip works on a clean environment. Order matters: the table
    # referencing the enums must be gone first (handled above).
    op.execute("DROP TYPE IF EXISTS expense_type")
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS receipt_status")
    op.execute("DROP TYPE IF EXISTS review_status")
