"""add jobs aliases and category budgets

Revision ID: cbd2c5157346
Revises: fa10823d17c1
Create Date: 2026-04-21 22:45:32.591969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbd2c5157346"
down_revision: Union[str, Sequence[str], None] = "fa10823d17c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("job_code", sa.String(length=64), nullable=True),
        sa.Column("job_name", sa.String(length=255), nullable=False),
        sa.Column("site_address", sa.String(length=512), nullable=True),
        sa.Column("contract_value_ex_gst", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_budget_ex_gst", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "completed", name="job_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("job_code"),
    )
    op.create_table(
        "job_aliases",
        sa.Column("alias_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("alias_text", sa.String(length=255), nullable=False),
        sa.Column("alias_text_normalized", sa.String(length=255), nullable=False),
        # ``language_code`` already exists as a Postgres ENUM type (owned by
        # the users migration). ``create_type=False`` tells SQLAlchemy not
        # to re-emit ``CREATE TYPE language_code`` here.
        sa.Column(
            "language_code",
            postgresql.ENUM("en", "zh", name="language_code", create_type=False),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("alias_text_normalized", name="uq_job_aliases_alias_normalized"),
    )
    op.create_table(
        "job_category_budgets",
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("budget_amount_ex_gst", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("budget_id"),
        sa.UniqueConstraint("job_id", "category_id", name="uq_job_category_budgets_job_category"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_category_budgets")
    op.drop_table("job_aliases")
    op.drop_table("jobs")
    # Autogenerate does not drop the Postgres ENUM type created alongside
    # the ``jobs`` table; drop it explicitly so a downgrade + upgrade
    # round-trip works on a clean environment. Order matters: the table
    # referencing the enum must be gone first (handled above).
    # ``language_code`` is owned by the users migration and is intentionally
    # NOT dropped here.
    op.execute("DROP TYPE IF EXISTS job_status")
    # ### end Alembic commands ###
